<?php
$Request = new SimpleXMLElement('<Request/>');
$Request->addChild('Version', "2");
$Authentication = $Request->addChild('Authentication');
$Authentication->addChild('UserID', "LodeStar");
$Authentication->addChild('Password', "TestAccoun");
$Request->addChild('TransactionDate', "");
$Request->addChild('ClientTransactionID', "");
$Request->addChild('Guarantee', "true");
$Request->addChild('Purpose', "GFE");
$ErnstRequest = $Request->addChild('ErnstRequest');
$ErnstRequest->addChild('Version', "1");
$Options=$ErnstRequest->addChild('Options');
for ($i=1; $i<3; $i++) {
$Option=$Options->addChild('Option');
$Option->addChild('Name', "");
$Option->addChild('Value', "");
}
$ErnstRequest->addChild('TransactionCode', "100");
$ErnstRequest->addChild('DataSource', "");
$Property=$ErnstRequest->addChild('Property');
$Property->addChild('Page', "PA005");
$Property->addChild('City', "");
$Property->addChild('County', "");
$Property->addChild('State', "");
$Property->addChild('FullAddress', "");
$Property->addChild('EstimatedValue', "250000.0");
$Property->addChild('MortgageAmount', "200000.0");
$Property->addChild('OriginalDebtAmount', "0.0");
$Property->addChild('UnpaidPrincipalBalance', "0.0");
$Property->addChild('Title', "");
$Property->addChild('TitleAmount', "0.0");
$Property->addChild('OwnersTitleAmount', "0.0");
$Property->addChild('OriginalTitleAmount', "0.0");
$Property->addChild('OriginalMortgageDate', "");
$StateQuestions=$Property->addChild('StateQuestions');
$StateQuestions->addChild('Q1', "");
for ($i = 1; $i <= 50; ++$i) {
    $StateQuestions->addChild("Q$i", "");
};
for ($i = 1; $i <= 50; ++$i) {
    $StateQuestions->addChild("V$i", "");
};
$NumberOfPages=$ErnstRequest->addChild('NumberOfPages');
$NumberOfPages->addChild('Mortgage', "127");
$NumberOfPages->addChild('Deed', "127");
$Mortgage=$ErnstRequest->addChild('Mortgage');
$Mortgage->addChild('AmendmentModificationPages', "127");
$Index=$Mortgage->addChild('Index');
$Index->addChild('NumberOfGrantors', "0");
$Index->addChild('NumberOfGrantees', "0");
$Index->addChild('NumberOfSurnames', "0");
$Index->addChild('NumberOfSignatures', "0");
$Deed=$ErnstRequest->addChild('Deed');
$Deed->addChild('AmendmentModificationPages', "127");
$Index=$Deed->addChild('Index');
$Index->addChild('NumberOfGrantors', "0");
$Index->addChild('NumberOfGrantees', "0");
$Index->addChild('NumberOfSurnames', "0");
$Index->addChild('NumberOfSignatures', "0");
$Assignment=$ErnstRequest->addChild('Assignment');
$Assignment->addChild('Pages', "127");
$Assignment->addChild('NumberOfAssignments', "0");
$Index=$Assignment->addChild('Index');
$Index->addChild('NumberOfGrantors', "0");
$Index->addChild('NumberOfGrantees', "0");
$Index->addChild('NumberOfSurnames', "0");
$Index->addChild('NumberOfSignatures', "0");
$Release=$ErnstRequest->addChild('Release');
$Release->addChild('Pages', "127");
$Release->addChild('NumberOfReleases', "0");
$Index=$Release->addChild('Index');
$Index->addChild('NumberOfGrantors', "0");
$Index->addChild('NumberOfGrantees', "0");
$Index->addChild('NumberOfSurnames', "0");
$Index->addChild('NumberOfSignatures', "0");
$Subordination=$ErnstRequest->addChild('Subordination');
$Subordination->addChild('Pages', "127");
$Subordination->addChild('NumberOfSubordinations', "0");
$Index=$Subordination->addChild('Index');
$Index->addChild('NumberOfGrantors', "0");
$Index->addChild('NumberOfGrantees', "0");
$Index->addChild('NumberOfSurnames', "0");
$Index->addChild('NumberOfSignatures', "0");
$POA=$ErnstRequest->addChild('POA');
$POA->addChild('Pages', "127");
Header('Content-type: text/xml');
print($Request->asXML());
?>